Repository rowanlovejoy/pec-project, pull requests merged in 2019-04, with the labels that each got.

#66 Reference comments
  PEC-App/Assets/Scripts/Events/EventListener.cs
  PEC-App/Assets/Scripts/Events/GameEvent.cs
  PEC-App/Assets/Scripts/StreamVideo.cs
Labels: Documentation

#68 Aspect ratio changes
  PEC-App/Assets/Animations/Day.anim
  PEC-App/Assets/Animations/EndPanelSlideInAnimation.anim
  PEC-App/Assets/Animations/EndPanelSlideOutAnimation.anim
  PEC-App/Assets/Animations/Night.anim
  PEC-App/Assets/Prefabs/Infomation Screen.prefab
  PEC-App/Assets/Scenes/MasterScene.unity
Labels: Art, GUI

#69 Animation lengths decresed and changed applied to prefab
  PEC-App/Assets/Animations/Idle.anim
  PEC-App/Assets/Animations/QuickEnd.anim
  PEC-App/Assets/Animations/Sunrise.anim
  PEC-App/Assets/Animations/Sunset.anim
  PEC-App/Assets/Prefabs/Simulation.prefab
  PEC-App/Assets/Scenes/MasterScene.unity
Labels: Art, Bug Fix

#67 End ratings adjustment
  PEC-App/Assets/Prefabs/Stats Screen.prefab
  PEC-App/Assets/Prefabs/pnl_EndScreenPanel.prefab
  PEC-App/Assets/Scenes/MasterScene.unity
  PEC-App/Assets/Scripts/EndRatingsCalculator.cs
  PEC-App/Assets/Scripts/StatsScreenCalculator.cs
Labels: Functionality, GUI

#74 Simulation Display Clock
  PEC-App/Assets/Animations/Clock.controller
  PEC-App/Assets/Animations/Clock.controller.meta
  PEC-App/Assets/Animations/ClockHandsSpinningAnimation.anim
  PEC-App/Assets/Animations/ClockHandsSpinningAnimation.anim.meta
  PEC-App/Assets/Prefabs/Clock.prefab
  PEC-App/Assets/Prefabs/Clock.prefab.meta
  PEC-App/Assets/Prefabs/Simulation.prefab
  PEC-App/Assets/Scenes/MasterScene.unity
  PEC-App/Assets/Scripts/AnimPlaybackSpeedAdjuster.cs
  PEC-App/Assets/Scripts/AnimPlaybackSpeedAdjuster.cs.meta
  PEC-App/Assets/Scripts/CoreAlgorithm.cs
  PEC-App/Assets/Testing Scenes/RowanTest.unity
  PEC-App/Assets/Visual Assets/Sprites/Simulation Sprites/Clock.png
  PEC-App/Assets/Visual Assets/Sprites/Simulation Sprites/Clock.png.meta
  PEC-App/ProjectSettings/TagManager.asset
Labels: Art

#75 Quit button recolour
  PEC-App/Assets/Scenes/MasterScene.unity
Labels: GUI

#76 Close App Confirmation Dialogue
  PEC-App/Assets/Animations/CloseConfirmDialogueSlideInAnimation.anim
  PEC-App/Assets/Animations/CloseConfirmDialogueSlideInAnimation.anim.meta
  PEC-App/Assets/Animations/CloseConfirmDialogueSlideOutAnimation.anim
  PEC-App/Assets/Animations/CloseConfirmDialogueSlideOutAnimation.anim.meta
  PEC-App/Assets/Animations/pnl_CloseConfirmDialogue.controller
  PEC-App/Assets/Animations/pnl_CloseConfirmDialogue.controller.meta
  PEC-App/Assets/Prefabs/Close Button .prefab
  PEC-App/Assets/Prefabs/Close Confirm Dialogue.prefab
  PEC-App/Assets/Prefabs/Close Confirm Dialogue.prefab.meta
  PEC-App/Assets/Scenes/MasterScene.unity
Labels: Functionality, GUI

#77 Animation added to fan blades
  PEC-App/Assets/Animations/ExtractorFan.controller
  PEC-App/Assets/Animations/ExtractorFan.controller.meta
  PEC-App/Assets/Animations/SpinningFanBlades.anim
  PEC-App/Assets/Animations/SpinningFanBlades.anim.meta
  PEC-App/Assets/Prefabs/Simulation.prefab
Labels: Art
